name: Build and upload release to PyPI

on:
  - pull_request
  - push

jobs:
  build_sdist:
    # Make a plain source distribution with nothing precompiled.
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build SDist
      run: pipx run build --sdist
    - uses: actions/upload-artifact@v3
      with:
        name: sdist
        path: dist/*.tar.gz

  upload_all:
    name: Upload release to PyPI
    # Upload all wheels and sdist to pypi
    needs: 
      - build_sdist
      - test_x86_wheels
      - test_linux_aarch64_wheels
    runs-on: ubuntu-latest
      # if: github.event_name == 'release' && github.event.action == 'published'
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pyoorb
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: sdist
        path: ./sdist/
    - uses: actions/download-artifact@v3
      with:
        name: x86_wheels
        path: ./x86_wheels/
    - uses: actions/download-artifact@v3
      with:
        name: aarch64_wheels
        path: ./aarch64_wheels/
    - name: Combine artifacts
      run: |
        mkdir dist
        mv sdist/* dist
        mv x86_wheels/* dist
        mv aarch64_wheels/* dist
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
